language: php

php:
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2

matrix:
    fast_finish: true

env:
    matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

sudo: false

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
- mkdir -p build/logs
- vendor/bin/phpunit

after_success:
- sh -c 'php vendor/bin/coveralls -v'
- CODECLIMATE_REPO_TOKEN="d1e37bee7168ee1746010705b5a942b491d6d984dfa22eb873d7914335eb3065" vendor/bin/test-reporter --stdout > codeclimate.json
- "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
- php vendor/bin/codacycoverage clover build/coverage/xml
