language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

matrix:
    fast_finish: true
    exclude:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"

env:
    matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

sudo: false

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
- mkdir -p build/logs
- php vendor/bin/phpunit --coverage-clover build/coverage/xml

after_success:
- sh -c 'php vendor/bin/coveralls -v'
- CODECLIMATE_REPO_TOKEN="ffc98cb63926402329f88aabec7e81d7a8de1c7c049e8bf2e11b81cb40b0220d" vendor/bin/test-reporter --stdout > codeclimate.json
- "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
- php vendor/bin/codacycoverage clover build/coverage/xml
